# Generated by Django 6.0 on 2025-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
