# Generated by Django 6.0 on 2025-12-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_is_deleted_alter_todo_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
