# Generated by Django 6.0 on 2025-12-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_time_spent_todo_time_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
    ]
