# Generated by Django 6.0 on 2025-12-15 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_owner_todo_shared_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='archive_flag',
            new_name='archived',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
