# Generated by Django 6.0 on 2025-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
