# Generated by Django 6.0 on 2025-12-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todorequest_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todorequest',
            name='is_notified',
        ),
    ]
