# Generated by Django 6.0 on 2025-12-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_todorequest_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todorequest',
            name='todo',
        ),
        migrations.AddField(
            model_name='todorequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
